apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-ping
spec:
  selector:
    matchLabels:
      app: node-ping
  template:
    metadata:
      labels:
        app: node-ping
    spec:
      containers:
      - name: node-ping
        image: YOUR_IMAGE_NAME
        command: ["/bin/bash"]
        args: ["-c", "/path/to/your/script.sh"]
